import numpy as np
import xgboost as xgb

### simple example
# load file from text file, also binary buffer generated by xgboost
dtrain = xgb.DMatrix('pima-indians-diabetes.txt.train')
dtest = xgb.DMatrix('pima-indians-diabetes.txt.test')

# specify parameters via map, definition are same as c++ version
param = {'max_depth':3, 'eta':1, 'silent':1, 'objective':'multi:softprob', 'num_class': 2 }

# specify validations set to watch performance
watchlist  = [(dtest,'eval'), (dtrain,'train')]
num_round = 2
bst = xgb.train(param, dtrain, num_round, watchlist)

# dump model
bst.dump_model('dump.raw.txt')

